### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [KyleCRat/TC359_Project_Five#1]
[Same problem as in project 4](https://github.com/KyleCRat/TC359_Project_Four/issues/1), and one other issue I'd like you to fix for this project. I *do* actually see some duplicate lines between view files. See if you can include [`content_for`](http://www.sinatrarb.com/contrib/content_for.html) in your project to fix this.

Although it's not specified on that page, you'll need to add `gem 'sinatra-contrib'` to your `Gemfile`, then run `bundle install` from the command line to install the library. And one more thing worth noting is that we're writing *modular* applications, rather than what Sinatra calls *classical* applications.

**Comment by KyleCRat** [comment]
Do you want me to pull the <div class="page-header"> and the last two trailing </div>'s? I left them because I felt removing them would make the page much more difficult to read for nearly zero extra typing. Is it better to have even that extra little bit in the layout file at the cost of readability?

But I have moved those lines to layout.erb for now and cleaned the directory. I also added the sinatra-contrib gem

**Comment by KyleCRat** [comment]
I did some more research and found out how to add keys to the yields. It should have no duplicate lines anymore.

**Comment by chrisvfritz** [comment]
:+1: Wonderful. In response to your excellent points:

> Do you want me to pull the div class="page-header" and the last two trailing /div's? I left them because I felt removing them would make the page much more difficult to read for nearly zero extra typing. Is it better to have even that extra little bit in the layout file at the cost of readability?

The reason for extracting as much repeated code as possible to the layout file isn't as much to reduce the amount of extra typing you have to do, but rather to prevent potential bugs when you make changes. 

For example, if you wanted to add a new class to the `page-header` div, like `text-center` for example, it could be easy to accidentally miss a page, especially as a project expands to dozens or even hundreds of pages.

In regards to readability, I just submitted [a pull request](https://github.com/KyleCRat/TC359_Project_Five/pull/2/files) that should demonstrate how we can modify the project to keep from having to use a `:body` key for the main content of every view. As you'll see, content that isn't in a `content_for` block is always passed to `yield` in the layout.

I hope that addresses your concerns! If not, I certainly don't mind discussing this in more detail. :smiley:

**Comment by KyleCRat** [comment]
That makes perfect sense. Thank you for the explanation. the pull request helped!
